on: [push]

jobs:
  safety:
    runs-on: ubuntu-latest
    name: "safety"
    steps:
      - uses: davidslusser/actions_python_safety@update_py_checkout
        with:
          options: "--debug"
          pip_install_command: "pip install -e .[dev]"
          python_version: "3.11"
