on: [push]

jobs:
    tox:
        name: run tests with Python ${{ matrix.python-version }}, Django ${{ matrix.django-version }}
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                python-version: ['3.8', '3.9', '3.10', '3.11']
                django-version: ['3.2', '4.0', '4.1', '4.2']

        steps:
        - uses: actions/checkout@v3
    
        - name: "Set up Python ${{ matrix.python-version }}"
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}
            cache: 'pip'
            cache-dependency-path: |
                setup.py
                tox.ini
                requirements/*.txt
       
        - name: "Install Python Dependencies"
          run: |
              python -m pip install --upgrade pip
              pip install -e .[dev]

        - name: "Tox tests"
          run: |
            tox -v
          env:
            DJANGO: ${{ matrix.django-version }}
